name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Surge
        run: npx surge ./build templatemarwan.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
